### ISSUE TITLE
Stopping the bot and what happens with funds held?

### ISSUE THREAD

**Issue by vamshi4001** [VertigoRay/GDAXBot#17]
Hi, This is a great bot, which I liked because of it's documentation and clear explanation. I've a quick question regarding the manual termination of bot, which is running on Mac terminal. What happens then? Will the orders will all be cancelled or should I do it manually? What's the hold amount bot's showing? Which number on terminal should be the one to know the profits/losses? Including a screenshot on readme would be great.

**Comment by hquan212** [comment]
If I am correct, the funds will be orders that are on Gdax, so they will still be there. They will execute if the market decides to move in that direction. You can log onto gdax to cancel the orders for peace of mind, but the standard deviation strategy tries to aim for a small profit instead of a loss.

**Comment by ghost** [comment]
```If I am correct, the funds will be orders that are on Gdax, so they will still be there. They will execute if the market decides to move in that direction. You can log onto gdax to cancel the orders for peace of mind, but the standard deviation strategy tries to aim for a small profit instead of a loss.``` Would be correct.
